### PR TITLE
update troubleshooting re docker push timeout error

### PR DESCRIPTION
**Pull request by jantley-ibm**

### CODE REVIEW

**Comment by jantley-ibm** [comment]
That's correct @stevemar

**Comment by jantley-ibm** [comment]
@stevemar or @navidsh -- are either of you able to merge this PR?  Merging is blocked for me since there is an outstanding review.

**Comment by stevemar** [comment]
@jantley-ibm i do not have permission to merge PRs in this repo by https://github.com/davco01a and https://github.com/s1cyan do. Ping.

**Comment by s1cyan** [comment]
I don't know why I have permission to merge in this repo but approved + merged 
¯\_(ツ)_/¯

**Comment by jantley-ibm** [comment]
Thanks @s1cyan !

**Pull request merged**
