### PR TITLE
add webhook example

### PR DESCRIPTION
**Pull request by dacleyra**
Add an example for using webhook

Depends on 
https://github.com/kabanero-io/kabanero-operator/pull/85

### CODE REVIEW

**Comment by marikaj123** [comment]
@alohr51 - Is it ready to be merged and closed?

**Comment by alohr51** [comment]
@marikaj123, @stephenkinder is listed as a reviewer so we need his approval first, and then The PR says there are conflicts so @dacleyra needs to clean up the conflicts in the README too. So it's not ready.

**Comment by dacleyra** [comment]
Added
https://github.com/kabanero-io/roadmap/issues/63

**Comment by alohr51** [comment]
@dacleyra can you resolve the conflict? I'll merge it in once you do.

**Comment by dacleyra** [comment]
The scripts moved to kabanero-foundation, canceling PR

**Comment by alohr51** [comment]
@dacleyra did you still want the added part for `ref/general/scripted-kabanero-foundation-setup.adoc ` merged in?

**Pull request closed without merging**
