### PR TITLE
Fix pv attrib

### PR DESCRIPTION
**Pull request by brutif**

### CODE REVIEW

**Comment by alohr51** [comment]
@jantley-ibm after you review/approve it, you should be the one to merge into master as well (unless others need to review) instead of PR originator.

**Comment by brutif** [comment]
@alohr51 he probably would have, had I not pushed the merge button to see if that cla mess got resolved.

**Comment by alohr51** [comment]
@brutif ah okay no prob, looks like you fixed it, hopefully the next PR doesn't have that same CLA problem now.

**Comment by jantley-ibm** [comment]
@alohr I was in a meeting and distracted but I thought I was not the only reviewer. In those cases I usually ask if they are ready for me to merge.

**Pull request merged**
